# Customize this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.67.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    sh "rm -fr ../Podfile.lock"
    cocoapods
    unlock_keychain(
	path:"pos",
	password:"a123456"
    )
    # carthage
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "pos"
  lane :pos do
    match
    increment_build_number_in_plist()
      increment_version_number_in_plist(
      version_number: '1.0'
    )
    gym(
      configuration: "Debug",
      output_name: "POSProject"
    )
    sh 'fir publish "../build/POSProject.ipa" -T "c93cadaa3ee8f931ef145e9976dec410"'
  end

  desc "qa"
  lane :qa do
    match
    increment_build_number_in_plist()
      increment_version_number_in_plist(
      version_number: '1.0'
    )
    gym(
      configuration: "Release-QA",
      output_name: "POSProject-QA"
    )
    sh 'fir publish "../build/POSProject-QA.ipa" -T "c93cadaa3ee8f931ef145e9976dec410"'
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://docs.fastlane.tools/advanced/#control-configuration-by-lane-and-by-platform
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://docs.fastlane.tools/#metrics
